version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_iesf
    ports:
      - "8089:80"
      - "8090:81"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_iesf
    volumes:
      - ./src:/var/www/html
    ports:
      - "9002:9000"
    networks:
      - app-network
  composer.test:
    image: composer/composer
    networks:
      - app-network
    ports:
      - "9001:9000"
    volumes:
      - "./composer:/composer"
      - ./src:/var/www/html
    depends_on:
      - php
    container_name: composer.test
    working_dir: /var/www/html
    command: composer install
  postgres:
    container_name: postgres_container_iesf
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: iesf
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - app-network
    restart: unless-stopped
  # redis:
  #   image: 'bitnami/redis:latest'
  #   container_name: redis
  #   ports:
  #     - 6379:6379
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   networks:
  #     - app-network
networks:
  app-network:
    driver: bridge
